module.exports = [
  {
    id: 1,
    name: "Santa Bauble",
    price: 5,
    image: "http://localhost:8080/images/image0.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 2,
    name: "Cactus plant pot",
    price: 5,
    image: "http://localhost:8080/images/image1.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 3,
    name: "Mika puppy",
    price: 5,
    image: "http://localhost:8080/images/image2.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 4,
    name: "Coasters",
    price: 5,
    image: "http://localhost:8080/images/image3.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 5,
    name: "A & C rabbit",
    price: 8,
    image: "http://localhost:8080/images/image4.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 6,
    name: "Dragons",
    price: 7,
    image: "http://localhost:8080/images/image5.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 7,
    name: "Baby shoes",
    price: 7,
    image: "http://localhost:8080/images/image6.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 8,
    name: "Baby hat",
    price: 7,
    image: "http://localhost:8080/images/image7.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
  {
    id: 9,
    name: "Gloves",
    price: 7,
    image: "http://localhost:8080/images/image8.jpg",
    description: "Handcrafted with crochet. Material: natural cotton.",
  },
];
