module.exports = [
  {
    id: 1,
    name: "Santa Bauble",
    price: 5,
    image: "http://localhost:8080/images/image0.jpg",
    description: "lorem ipsum",
  },
  {
    id: 2,
    name: "Cactus plant pot",
    price: 5,
    image: "http://localhost:8080/images/image1.jpg",
    description: "lorem ipsum",
  },
  {
    id: 3,
    name: "Mika puppy",
    price: 5,
    image: "http://localhost:8080/images/image2.jpg",
    description: "lorem ipsum",
  },
  {
    id: 4,
    name: "Coasters",
    price: 5,
    image: "http://localhost:8080/images/image3.jpg",
    description: "lorem ipsum",
  },
  {
    id: 5,
    name: "A & C rabbit",
    price: 8,
    image: "http://localhost:8080/images/image4.jpg",
    description: "lorem ipsum",
  },
  {
    id: 6,
    name: "Napkin",
    price: 7,
    image: "http://localhost:8080/images/image5.jpg",
    description: "lorem ipsum",
  },
  {
    id: 7,
    name: "Bauble",
    price: 5,
    image: "http://localhost:8080/images/image6.jpeg",
    description: "lorem ipsum",
  },
  {
    id: 8,
    name: "Shawl",
    price: 10,
    image: "http://localhost:8080/images/image7.png",
    description: "lorem ipsum",
  },
  {
    id: 9,
    name: "Lampshade",
    price: 50,
    image: "http://localhost:8080/images/image8.jpeg",
    description: "lorem ipsum",
  },
  {
    id: 10,
    name: "Napkin - small",
    price: 5,
    image: "http://localhost:8080/images/image9.jpg",
    description: "lorem ipsum",
  },
  {
    id: 11,
    name: "Bauble - small",
    price: 5,
    image: "http://localhost:8080/images/image11.png",
    description: "lorem ipsum",
  },
  {
    id: 12,
    name: "Baby shoes",
    price: 5,
    image: "http://localhost:8080/images/image12.png",
    description: "lorem ipsum",
  },
];
